//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class itacademy3 : DbContext
    {
        public itacademy3()
            : base("name=itacademy3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<possible_answers> possible_answers { get; set; }
        public virtual DbSet<question> question { get; set; }
        public virtual DbSet<rezult> rezult { get; set; }
        public virtual DbSet<test_theme> test_theme { get; set; }
        public virtual DbSet<user_table> user_table { get; set; }
    }
}
