//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class possible_answers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public possible_answers()
        {
            this.rezult = new HashSet<rezult>();
        }
    
        public int id_possible_answers { get; set; }
        public Nullable<int> id_question { get; set; }
        public Nullable<bool> correct_answer { get; set; }
        public Nullable<int> id_next_question { get; set; }
    
        public virtual question question { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rezult> rezult { get; set; }
    }
}
