//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rezult
    {
        public int id_rezult { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> id_question { get; set; }
        public Nullable<int> id_theme { get; set; }
        public Nullable<int> id_possible_answers { get; set; }
    
        public virtual possible_answers possible_answers { get; set; }
        public virtual question question { get; set; }
        public virtual user_table user_table { get; set; }
        public virtual test_theme test_theme { get; set; }
    }
}
